# Generated by Django 3.2.7 on 2021-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211009_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('phone', models.TextField(verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('address', models.TextField(verbose_name='Почтовый адрес')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
    ]
